### ISSUE TITLE
Unimplemented methods: set_zoom_xy and set_zoom_z

### ISSUE THREAD

**Issue by ludovicabrusaferri** [NikEfth/STIR#14]
The functions set_zoom_xy and set_zoom_z in: https://github.com/NikEfth/STIR/blob/0a54fca817d24aef1d022bc965a83d0095448b1a/src/include/stir/scatter/ScatterEstimation.h#L156-L158

are unimplemented. This creates an issue when STIR is built with swig matlab/python flag ON and the ScatterEstimation class is exported in swig.i (swig cannot handle unimplemented methods)

**Comment by NikEfth** [comment]
Alright will do it tonight ... thanks

**Comment by KrisThielemans** [comment]
These are currently  commented out to avoid problems.

**Comment by KrisThielemans** [comment]
This issue is not a TOF one, so should be recreated on the main STIR repo

**Comment by KrisThielemans** [comment]
I checked. These functions are currently commented out both on `master` and `tof_sino_UCL`
