### ISSUE TITLE
Error when calling forward via SIRF

### ISSUE THREAD

**Issue by AnderBiguri** [NikEfth/STIR#15]
Hi Nikos!

I am giving the `tic_sino_UCL` a go, via SIRF. 

When I forward project on my 32 core machine, it takes about 2.5h (it forward projects the data properly) but at some point, I assume in the end, errors as:

```
WARNING: read_data: error after reading from stream.

ERROR: ProjDataFromStream: error reading data

ERROR: ProjDataFromStream::get_viewgram: error in stream state before reading

(32 times above line)

terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
terminate called recursively
Aborted (core dumped)
```

----

# Slightly more info

I am trying to figure out proper TOF parameters for DMI 3Ring, but the current should be more or less correct (this is exactly DMI-3ring, but with TOF data added). To set up the acquisition data, I just load this template:

```
!INTERFILE  :=
!imaging modality := PT
name of data file := /dev/zero
originating system := Unknown
!version of keys := STIR4.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 5
matrix axis label [5] := timing positions
!matrix size [5] := 29
matrix axis label [4] := segment
!matrix size [4] := 53
matrix axis label [3] := view
!matrix size [3] := 272
matrix axis label [2] := axial coordinate
!matrix size [2] := { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 415
%TOF mashing factor := 1
minimum ring difference per segment :=  { -26,-25,-24,-23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26}
maximum ring difference per segment := { -26,-25,-24,-23,-22,-21,-20,-19,-18,-17,-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26}
Scanner parameters:= 
Scanner type := GE Discovery MI 3 rings
Number of rings                          := 27
Number of detectors per ring             := 544
Inner ring diameter (cm)                 := 74.22
Average depth of interaction (cm)        := 0.94
Distance between rings (cm)              := 0.552296
Default bin size (cm)                    := 0.2206
View offset (degrees)                    := -4.399
Maximum number of non-arc-corrected bins := 415
Default number of arc-corrected bins     := 401
Energy resolution := 0.0944
Reference energy (in keV) := 511
Number of TOF time bins := 29
Size of timing bin (ps) := 169.26
Timing resolution (ps) := 380
Number of blocks per bucket in transaxial direction         := 4
Number of blocks per bucket in axial direction              := 3
Number of crystals per block in axial direction             := 9
Number of crystals per block in transaxial direction        := 4
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 1
Number of crystals per singles unit in transaxial direction := 1
end scanner parameters:=
effective central bin size (cm) := 0.219737
number of time frames := 1
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=
```

if I then just do 

```
acq_data_template=stir.AcquisitionData('DMI_template_tof.hs')
acq_data=acq_data_template.clone()
acq_data.fill(0.0)
print(acq_data.as_array().shape) #this works :)
```

However, when then I plug it in my code for forward projection, that sets the acquisition model as: 
```
# hopefully self explanatory inputs :) 
def set_up_pet_model(acq_data_template,att_image,image_template):
    # Create sensitivity model based on the acquisition model and attenuation image
    asm_attn = stir.AcquisitionSensitivityModel(attn_image, stir.AcquisitionModelUsingRayTracingMatrix())
    asm_attn.set_up(acq_data_template)
    # now forward project a white image with the sensitivity model, and store them back in a new sensitivity model (to save computational time)
    asm_attn = stir.AcquisitionSensitivityModel(asm_attn.forward(acq_data_template.get_uniform_copy(1)))

    # reuse this code to set up pet model (note we are just using template info here, not data)
    acq_model = stir.AcquisitionModelUsingRayTracingMatrix()
    acq_model.set_acquisition_sensitivity(asm_attn)
    acq_model.set_up(acq_data_template,image_template)
    return acq_model
```

Then when I run the forward projection. 

----

I can share a full Minimum complete example if that will help more.

Do you have any idea or where can I look to start debugging this stuff?
This of course may be a SIRF issue, but just adding the info here as its not merged in master and then in SIRF yet!

**Comment by AnderBiguri** [comment]
I think it has to do with the header file with the scanner info, as the header from Alex (D710) works fine.

**Comment by KrisThielemans** [comment]
the STIR forward projection doesn't read anything. SIRF forward projection does STIR forward projection and then applies sensitivity model. In this case, it'll "read" the ACFs that you compute first. I'm therefore assuming that there's something wrong with that. I guess you could test that by removing the lines related to the `asm_attn`, but 2.5 hours to test that might take a bit long.

However, I'm not so sure what SIRF will do for the `asm_attn.forward(acq_data_template.get_uniform_copy(1)`. It's possible that it will make a TOF sinogram, which isn't really appropriate. I guess I'd try to save that output (it's an `AcquisitionData`) to file to check. But you could also give it a non-TOF template, to force it to do the proper thing.

Of course, you want to run all this with far fewer data first to  check (Easiest is to remove nearly all segments).

**Comment by AnderBiguri** [comment]
@KrisThielemans I will definetly try those things, thanks for the tips. 

Albeit I haven't really checked the data much, I have however run the code using Alex' D710 tof header, and it run OK and returned a TOF sinogram, so I am not entirely sure this is not a bug or an uncatched exception. When I used a different set of TOF parameters, it also errored with some non-clear message, but it ended up being that the scanner info was not correct.

**Comment by KrisThielemans** [comment]
no error doesn't mean it did the proper thing...

please do the check above :-)

**Comment by NikEfth** [comment]
Hi, 
I see that you already are on a great path here. 
~~I want to add that 2.5 hours is normal if you unlist one TOF bin at the time. 
To speed it up, you can increase the number of TOF bins in memory.~~
This is only for listmode.

However, I see that the originating system on the top of the headerfile is Unknown. 
I cannot think what in particular it could cause. But try to fix that. 

I understand that you just forward project a phantom's image?

**Comment by AnderBiguri** [comment]
Thanks for the answer!
I made the header. As the DMI 3 ring does not have TOF info, I think with the scanner name it was creating non TOF sinogram (I think, tried few things). In any case, the scanner is the DMI and it has all the DMI numbers. I only use it as a template.

I think it also takes very long because it has 29 TOF bins.

Silly question: 29 is prime. Is there a way to non uniformly mash these bins? For now it doesn't matter too much, I'm doing simulation, but for the future...

**Comment by NikEfth** [comment]
` Is there a way to non uniformly mash these bins?`
I am sorry, the question, is that you actually don't want to do uniform mashing?
In that case that would be very interesting and I can make this happen for you.

**Comment by AnderBiguri** [comment]
Well, it's not that I don't necessarily want it, but if the number of bins is prime, then you can't mash it uniformly! The number of bins in the DMI is 29!

**Comment by NikEfth** [comment]
I see your point. 
But with TOF mashing that is not a problem. You just round up and make sure that after mashing 
you have an odd number of bins. 
Rounding down still works but you might lose some events near the edges of the coincidence window. 

EDIT: 
Depending on the mashing, you might have to "add" one bin to keep the central, centred.

**Comment by KrisThielemans** [comment]
except that at the moment we always assume that same total length, so it would stretch things. This would therefore need code modifications.

For the future!

**Comment by NikEfth** [comment]
> except that at the moment we always assume that same total length, so it would stretch things. 

~~Not sure about that, we calculate the length of the LOR (coincidence window) but never use it. We start from the centre of the LOR (whatever that means) and go towards the edges. The length comes from the detectors~~
I misunderstood your comment. Sure ok. 
But that would be an easy modification.

**Comment by NikEfth** [comment]
As I said previously, the worst that can happen is losing events if you don't have enough bins. Or nothing if you have more bins.

**Comment by AnderBiguri** [comment]
I close this because the problem in the first post can not be reproduced, but will have more questions! :)
