### ISSUE TITLE
TOF sinogram created from non-TOF template for TOF mashing factor = 1

### ISSUE THREAD

**Issue by NicoleJurjew** [NikEfth/STIR#27]
When I create acquisition data from a template sinogram which is non-TOF, so it only has 4 dimensions, but contains the following lines:

```
%TOF mashing factor := 1
Number of TOF time bins :=33
Size of timing bin (ps) :=143.231
Timing resolution (ps) :=214
```

a TOF-sinogram is created. As long as only the line %TOF mashing factor :=1 is included, but the other lines are deleted, non-TOF data is created.

**Comment by robbietuk** [comment]
Can you detail the scanner/commands used?

**Comment by NicoleJurjew** [comment]
I created and wrote a sirf.STIR.AcquisitionData('Vision') object after implementing [ashgillman:clean-tof_sino_UCL ](https://github.com/UCL/STIR/pull/918/commits/59ab3eadadfe514fa5d4a823a6db305c9193567a).

Then I manually remove/alter the lines
```
number of dimensions := 5
matrix axis label [5] := timing positions
!matrix size [5] := 13
```

When I create a new AcquisitionData() object from that file, it contains TOF-bins. I'll be happy to upload the file, but github won't let me because of the unknown file ending.

**Comment by KrisThielemans** [comment]
I think this is not so suprising. If the the TOF mashing factor is 1, and there is TOF info on the scanner, the code will enable TOF for the data. I guess it should have returned a TOF sinogram with only 1 TOF bin though. Or thrown an error that this isn't supported.

**Comment by KrisThielemans** [comment]
Note: the current `recon_test_pack/run_test_listmode.sh` "uses" this behaviour to do TOF tests (i.e. the template passed is non-TOF, but `lm_to_projdata` ignores this). We will need to use a TOF template there as soon as we fix this.
