### ISSUE TITLE
listmode files with compressed proj_data_info are broken

### ISSUE THREAD

**Issue by KrisThielemans** [NikEfth/STIR#33]
The `CListEventCylindricalScannerWithDiscreteDetectors` constructor no longer "uncompresses" the `proj_data_info`. The constructor currently just copies the argument
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/include/stir/listmode/CListEventCylindricalScannerWithDiscreteDetectors.inl#L25-L27
while on `master` it [creates a new `proj_data_info` with span=1 and without view mashing](https://github.com/UCL/STIR/blob/756949482fb6a593e4b5e224b329f93bc810eb96/src/include/stir/listmode/CListEventCylindricalScannerWithDiscreteDetectors.inl#L28-L35).
(The code change on the TOF branch was at https://github.com/NikEfth/STIR/commit/66df04293f7dc29e271e1e3f03c017d62163ca97)

This means that when using an argument with span>1 or view mashing>1, (which would be used for a listmode file format that has one of those, such as for the mCT), the code will crash.

It seems to me that this needs to be reversed to be identical to `master`.

The question is then what needs to be done with TOF mashing. It seems to make logical sense to set TOF mashing to 1 for this `uncompressed_proj_data_info`. In fact, this is currently required as we used (mashed) `get_tof_bin()` to find (unmashed) `det_pos.timing_pos_num()`
https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/listmode_buildblock/CListRecordROOT.cxx#L39-L49.
(`uncompressed_proj_data_info.get_tof_mash_factor()>1` could be supported by switching to `get_unmashed_tof_bin(), but that is currently broken, see https://github.com/NikEfth/STIR/issues/32). 

Upshot of all this is that the ***current listmode code only supports an (input) `proj_data_info` of span=1, view mashing =1 , tof mashing = 1***. It will (or at least should) crash when used otherwise. (Note that the template used for `LmToProjData` can have mashing. The above applies for the `proj_data_info` used to decode the listmode file).

The next question is then which listmode files would use compression:
- GE listmode files are uncompressed
- currently ECAT8_32 only supports the mMR, which is non-TOF and uncompressed. However, the mCT uses both view and tof mashing in listmode I believe.
- for ROOT files, the constructor will be called with a [TOF mashing factor](https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/listmode_buildblock/CListModeDataROOT.cxx#L180-L186). This defaults to 1, but can be [set from the .hroot file](https://github.com/NikEfth/STIR/blob/1422b9d447dba8dd0401cd10b294c0e4f218df13/src/listmode_buildblock/CListModeDataROOT.cxx#L69). Given all of the above, I believe that a ***TOF mashing factor > 1 in the .hroot will create incorrect results***.

**Comment by danieldeidda** [comment]
I am try to push this on a new branch but getting this:
 ! [remote rejected]     revertUncopress -> master (permission denied)
error: failed to push some refs to 'https://github.com/NikEfth/STIR.git'

**Comment by KrisThielemans** [comment]
not sure what you're trying, but you cannot push to nikeft, only to your own fork. Then do PR to nikefth/tof_sino_UCL..

**Comment by KrisThielemans** [comment]
> It seems to me that this needs to be reversed to be identical to `master`.

This was unclear. I didn't mean "reverting to using `Scanner` as input argument, but "changing the new `ProjDataInfo` constructor to use the code on `master` to construct an uncompressed projdatainfo.

This is now attempted in #55.

**Comment by KrisThielemans** [comment]
Closed by https://github.com/NikEfth/STIR/pull/55
