### ISSUE TITLE
Adding info for processing min TOF bin for Lm_to_Projdata.cxx in tof_sino_UCL

### ISSUE THREAD

**Issue by pw351** [NikEfth/STIR#7]
Currently the unlisting prints out information that it starts processing from TOF bin number min_bin +1.
It seems that it skips the minimum bin but actually it doesnot. 
Maybe it would be a good idea to just add a line there saying Processing next batch of segments for start TOF bin "min tof bin number".

**Comment by KrisThielemans** [comment]
closing as obsolete (I think)
